### PR TITLE
updated ParParticleFilter to clean up duplicate code in run() and

### PR DESCRIPTION
**Pull request by curtwu**
update run() and advanceTime() with shared indices code
fix missing ParticleFilter.par type
streamline makeWeightedParticle

### CODE REVIEW

**Comment by lfkellogg** [comment]
ParParticleFilter.scala: Looks great! Very clean.

ParticleFilter.scala: Now that I'm looking at it again, I bet that one liner would be clearer as:

```
val satisfied = currentUniverse.conditionedElements.forall { x => x.conditionSatisfied }
```

I just checked and forall() also breaks once it finds a case that doesn't satisfy the predicate. If you agree, do you want to go ahead and make that change before I do the merge?

Also,

```
math.exp(currentUniverse.constrainedElements.foldLeft(0.0)((b,a) => b + a.constraintValue))
```

I was confused here at first, but I see you just moved the multiplication up into log space. Looks good!

**Comment by curtwu** [comment]
The forall change makes sense -- removing 2 negations is always a good idea
Yeah, I moved the multiplication into log space because (1) I figured that was the whole point of being in log space; (2) only one call to math.exp

**Comment by lfkellogg** [comment]
One last thing: could you remove the ParticleFilter.par definition you added? I actually added the same thing when you weren't looking after I noticed I had forgotten it. There might be an easier way for me to resolve the conflict but I'm not sure what that would be.

**Comment by curtwu** [comment]
should be all set now

**Comment by lfkellogg** [comment]
It says it can't automatically merge it, I'm pretty sure because you're branch doesn't have my latest commit where I added the .par reference. Somehow yours is conflicting with mine. It says I can resolve it manually on the command line but it's not immediately obvious how. If you want to try and pull my commits into your branch, go ahead, otherwise I'll take another stab at this later when I get a minute. I'm glad we're figuring this git stuff out!

**Comment by curtwu** [comment]
holy crap -- that was way harder than it had to be

**Pull request merged**
